### ISSUE TITLE
go client has mention of PHP

### ISSUE THREAD

**Issue by Zamua** [launchdarkly/api-client-go#16]
[This line](https://github.com/launchdarkly/api-client-go/blob/058783fc8027f06ab72d811698c914d9e867cf15/docs/Environment.md?plain=1#L14) mentions php. is this intentional?

Here's the string inlined:
```
The default time (in minutes) that the PHP SDK can cache feature flag rules locally
```

**Comment by mmrj** [comment]
Hi @Zamua , 

Thanks for your question! Yes, this is intentional. 

The api-client-go is one of the [generated client libraries](https://apidocs.launchdarkly.com/#section/Overview/OpenAPI-(Swagger)-and-client-libraries) we provide to make it a little easier to work with our REST API. You can use the REST API to perform functions that you might otherwise perform using the LaunchDarkly user interface.

The LaunchDarkly SDKs are for integrating LaunchDarkly with your application. When your application starts up, your code should initialize the LaunchDarkly SDK you're working with. When a customer encounters a feature flag in your application, your code should use the SDK to evaluate the feature flag and retrieve the appropriate flag variation. 

The line you mention is a property that's specific to our PHP SDK, but returned by a request to our REST API. To learn more, read [Comparing LaunchDarkly's SDKs and REST API](https://docs.launchdarkly.com/guide/api/comparing-sdk-rest-api).
