### ISSUE TITLE
When will the API client support multivariate flags?

### ISSUE THREAD

**Issue by estensen** [launchdarkly/api-client-go#3]
Hi, we're looking to set a users flag value to a string, but this API client seems to only support bool flags (`PutFlagSetting`). Is the best alternative to user the API directly?

**Comment by eli-darkly** [comment]
There are a couple of issues here.

First, it does seem like the definition of PutFlagSetting— not just in this generated Go client, but in the API spec that drives all of those clients and also our [API documentation](https://apidocs.launchdarkly.com/reference#update-flag-setting-for-user)— is wrong, in that it doesn't accurately describe how the endpoint really works. The endpoint does allow a flag value of any type, but the API spec has defined it as a boolean. So, if you do want to use this particular endpoint (`/users/{projectKey}/{environmentKey}/{userKey}/flags/{featureFlagKey}`) to update a non-boolean flag, then yes, currently you would need to talk to the API directly by some other means rather than this client.

That's something we should fix, but we typically wouldn't fix it in a regular patch release, because it would change the type signatures and therefore be a breaking change for anyone who's currently using the client.

However, to be clear, that endpoint is only a shortcut. The LaunchDarkly feature flag model does not really work in terms of "the value for user A is B"— there are many ways to arrange a flag so that a user will get a particular value. What the endpoint used by PutFlagSetting is really doing is:

1. Find out which variation of the flag corresponds to the value you specified (the default for boolean flags is that variation 0 is true and variation 1 is false, but that's not mandatory)
2. Check if the flag already has a "target individual users" list for that variation, and if not, create one.
3. Add the user key to that target list if it isn't already there.
4. If that user key was previously in a user target list for a different variation, remove it from there.

All of those individual things could be done with the API client as well, for either boolean or non-boolean flags; it would just be more tedious to do it that way.

**Comment by estensen** [comment]
Eventually got it working using the API.

For a while the API returned 204 while nothing was changed for the user or showed up in the audit log. But it turns out my payload was `settings`, not `setting`. There is a support ticket, but other people might also stumble upon this. Might be missing validation somewhere.

We have a special use case where we need to enable a feature one user at a time. After enabling the feature for everyone we might want to change the flag setting again, but this time for all users at the same time. Segments seems to be a good way of doing this. But I can't find docs for doing it with the API or the SDK. Is this going to be supported anytime soon?

**Comment by eli-darkly** [comment]
> But it turns out my payload was settings, not setting. There is a support ticket, but other people might also stumble upon this. Might be missing validation somewhere.

I'm fairly sure that none of the endpoints have strict validation of property names in JSON request bodies. The LD services are written in Go; the standard behavior of JSON deserialization in Go is that if an expected property is missing, it's treated the same as if it had an empty value, and if an unexpected property name is seen, it's simply ignored. So validation only applies to values that are actually present with a known property name. That does make it harder to spot errors of this kind, but it's unlikely that it will change soon because it would require non-trivial changes to the service implementation.

> After enabling the feature for everyone we might want to change the flag setting again, but this time for all users at the same time. Segments seems to be a good way of doing this. But I can't find docs for doing it with the API or the SDK

It depends on what you mean by "doing it" in this context.

If you already have a user segment that has all the desired users in it, and your feature flag has a rule like "if the user is in segment X, serve variation 1", then it sounds like what you want to do is modify the flag rule. In that case you would use `FeatureFlagsApiService.PatchFeatureFlag`, which is the general mechanism for updating any property of a flag.

If instead what you want to do is to update the user segment itself, then you would use `UserSegmentsApiService.PatchUserSegment`.

Both of those APIs use the JSON Patch syntax; `PatchFeatureFlag` also accepts JSON Merge Patch operations. See the Updates section of [the API docs](https://apidocs.launchdarkly.com/reference) for more about this.

**Comment by estensen** [comment]
> That's something we should fix, but we typically wouldn't fix it in a regular patch release, because it would change the type signatures and therefore be a breaking change for anyone who's currently using the client.

When will there be a new release? Last API version in the API docs is from 2019, but I see there have been releases for this API client recently.

It would be nice if release notes could be provided. Or maybe they map 1-1 with the OpenAPI spec? It seems like two releases are created for each release: `5.0.2` and `v5.0.2`.


> It depends on what you mean by "doing it" in this context.

Add a user to an existing segment. 

> If you already have a user segment that has all the desired users in it, and your feature flag has a rule like "if the user is in segment X, serve variation 1", then it sounds like what you want to do is modify the flag rule so that it says "serve variation 2" or whatever. In that case you would use `FeatureFlagsApiService.PatchFeatureFlag`, which is the general mechanism for updating any property of a flag.
> 
> If instead what you want to do is to update the user segment itself, then you would use `UserSegmentsApiService.PatchUserSegment`.

It's not very clear to me how to add a user to a segment from the API docs. There are no examples doing anything similar.

**Comment by eli-darkly** [comment]
For clarity, I'll answer your points about releases first, and the segment API question in another comment.

> When will there be a new release? Last API version in the API docs is from 2019, but I see there have been releases for this API client recently.
> It would be nice if release notes could be provided. Or maybe they map 1-1 with the OpenAPI spec?

I can't say specifically when the next release will be; it depends on what issues we're fixing.

However, most releases don't involve a change in the _API_ version. As the API docs say, we increase the API version "every time we make a _breaking_ change". Most of the time when we update the APIs, we're just adding new ones (or newly supported parameters for existing ones) rather than making backward-incompatible changes to the existing ones.

So, many releases of the API client libraries are to add support for new endpoints or new parameters. But others are to fix issues like this one where the OpenAPI spec doesn't accurately describe the existing endpoints. The versioning is based on semantic versioning rules from the point of view of both the API functionality and application code that uses the libraries. So, if we fix a problem in such a way that it doesn't add any new functionality and doesn't break any existing code, then that's a patch release. If we add new functionality and don't break any existing code, then that's a minor release.

> It seems like two releases are created for each release: 5.0.2 and v5.0.2

That's two tags, not two releases, and this only happens for the Go client. Our release process always creates a tag called X for every release version X, because that's how the releases are named in the GitHub release list— every release has a tag with the same name. But Go, ever since it added support for modules, expects a tag called `vX` rather than just X. So we have both.

**Comment by eli-darkly** [comment]
> It's not very clear to me how to add a user to a segment from the API docs. There are no examples doing anything similar.

All of the `Patch` calls support the JSON Patch request format, and some, including `PatchUserSegment`, also support JSON Merge Patch; there are links to both of those specifications from the API docs.

Both JSON Patch and JSON Merge Patch are very general-purpose ways of describing a change to something in terms of the API's JSON representation of that thing. So, in order to know how to specify that change you need to look at the existing JSON representation first.

The simplest way to do that is to query the GET version of the endpoint, for instance `curl -H 'Authorization:$API_KEY' https://app.launchdarkly.com/api/v2/segments/$PROJECT_KEY/$ENV_KEY/$SEGMENT_KEY`. Do this for an existing user segment that has some users in it, and you'll see where the user keys are in the JSON data structure. For instance (omitting some properties that aren't relevant here):

```json
{
  "name":"My Segment",
  "key":"my-segment",
  "included":["user-key-1", "user-key-2"],
  "excluded":[]
}
```

So you see two arrays of user keys that correspond to the "included users" and "excluded users" lists in the UI. To add a user to the segment, you would add a new element to `included`. Adding an element to an array is not really supported in JSON Merge Patch (you would need to re-specify all of the values for the array), but in JSON Patch it would look like this:

```
{ "op": "add", "path": "/included/-", "value": "user-key-3" }
```

Those properties correspond to the properties of the `PatchOperation` type in the Go API client.

**Comment by eli-darkly** [comment]
Sorry, one thing I forgot to answer:

> It would be nice if release notes could be provided

The various API client libraries like `api-client-go` and `api-client-java` are generated automatically from the base repository `ld-openapi`. So you can see the release history there: https://github.com/launchdarkly/ld-openapi/releases

Our release process doesn't easily support mirroring the release list to all the generated repos. But we do intend to update the Readme content for the generated repos to make these kinds of things clearer.

**Comment by estensen** [comment]
Thanks for answering all my questions! 🙌🏻 

Just one more: For [Bulk user targeting](https://docs.launchdarkly.com/home/flags/bulk-targeting):
>Very large lists of named users increases the size of the payload the SDK fetches when initializing, as well as the memory footprint of the SDK. Lists of over 50,000 individual users are not supported for flags or segments in LaunchDarkly.
>
>We recommend not exceeding a few thousand individual users across your flags and segments. Instead, use custom attributes to target a large number of individual users. Custom attributes let you assign an attribute to the users who should receive the feature flag and then set up the targeting rules to serve the flag to users who have that attribute, so you can target groups of users without increasing the size of the payload.

Does this imply that segments or feature flags shouldn't contain more than a few thousand users? Or is it a recommendation to not change too many users at a time?

If it's a limit, I think we need to use custom attributes instead.

**Comment by eli-darkly** [comment]
It's a general recommendation. As it says, there is an actual limit which is much higher than "a few thousand", but if you're adding lists of thousands of users to feature flags on a regular basis then it's _possible_ that you're not using the system in the most efficient way.

Without knowing more about how users are represented in your application and what kind of feature flagging you're trying to do, it's impossible to say whether individual user targeting or custom user attributes would be a better way to go. And this really isn't the best place to have that discussion, not just because it doesn't relate to the API client, but also because it might involve discussing details of your system in a public forum. My recommendation would be that you go through support.launchdarkly.com and talk with our support team about the many ways that feature flags can be configured.
